### ISSUE TITLE
Questions about the dataset

### ISSUE THREAD

**Issue by yzb1997** [zzh-tech/BiT#1]
First of all, congratulations on such a great public work, but I have some questions to ask you：

I would like to use your dataset to train a single image input, single image output deblurring model, I want to know how to find the sharp image corresponding to the blurred image.

**Comment by zzh-tech** [comment]
Hi, thank you for your interest!
If you want to do one-to-one mapping deblurring problem.
Please use this real-world dataset:
https://github.com/zzh-tech/ESTRNN

**Comment by yzb1997** [comment]
Are the two datasets the same?

**Comment by zzh-tech** [comment]
No, BSD is bigger but can only do one-to-one deblurring.
