### ISSUE TITLE
How to deblur a video?

### ISSUE THREAD

**Issue by Talegqz** [zzh-tech/BiT#2]
Thanks for your excellent work.
I have found that the demo is capable of deblurring images using a set of three images. 
However, I am wondering if you could offer some guidance on how to deblur a video instead. 
Would it be appropriate to deblur each frame using information from the previous and next frames? 
I appreciate your help with this matter.

**Comment by zzh-tech** [comment]
> Would it be appropriate to deblur each frame using information from the previous and next frames?

Yes, it should be easy.
You can extract each frame from the video and modify the inference code slightly, _e.g._, just using a loop to infer with three frames in order.

**Comment by Talegqz** [comment]
Thanks for your help!
