### ISSUE TITLE
A minor issue with the config .yaml files 

### ISSUE THREAD

**Issue by nooobkevin** [zzh-tech/BiT#8]
Hello, I am trying to run the example code you provided and noticed a potential issue with the .yaml config files. It seems that all of them contain absolute paths instead of relative paths:
![issue](https://github.com/zzh-tech/BiT/assets/55838818/6c769698-72d4-4393-b49d-d8af36b69846)

I believe this might not be intended and wanted to bring it to your attention. Thank you for your work, and I'm excited to try it out!

**Comment by zzh-tech** [comment]
Hi, replacing the path with yours should work.
